// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWoSvHmZk5LQ9s519i2B7O26xlVdY0W_Y',
    appId: '1:131605923272:web:faa7963c605998ec0a6cfd',
    messagingSenderId: '131605923272',
    projectId: 'mynotes-flutter-deb31',
    authDomain: 'mynotes-flutter-deb31.firebaseapp.com',
    storageBucket: 'mynotes-flutter-deb31.appspot.com',
    measurementId: 'G-TBR8L9TGWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAP7iRyCgLkUNwOVN7b0OfWKqVSN7n3Kw',
    appId: '1:131605923272:android:4b56ca496c32ef380a6cfd',
    messagingSenderId: '131605923272',
    projectId: 'mynotes-flutter-deb31',
    storageBucket: 'mynotes-flutter-deb31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAifs0PBNbu8S1QV2b7IYNp0NZ8feMtx0Q',
    appId: '1:131605923272:ios:4d7b248f2fbaf4c50a6cfd',
    messagingSenderId: '131605923272',
    projectId: 'mynotes-flutter-deb31',
    storageBucket: 'mynotes-flutter-deb31.appspot.com',
    iosClientId: '131605923272-o254140mi640jsr8a06tn72m9svi2qh6.apps.googleusercontent.com',
    iosBundleId: 'com.wathever.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAifs0PBNbu8S1QV2b7IYNp0NZ8feMtx0Q',
    appId: '1:131605923272:ios:4d7b248f2fbaf4c50a6cfd',
    messagingSenderId: '131605923272',
    projectId: 'mynotes-flutter-deb31',
    storageBucket: 'mynotes-flutter-deb31.appspot.com',
    iosClientId: '131605923272-o254140mi640jsr8a06tn72m9svi2qh6.apps.googleusercontent.com',
    iosBundleId: 'com.wathever.mynotes',
  );
}
